---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: metrics-server
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: metrics-server
  template:
    metadata:
      labels:
        app: metrics-server
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: metrics-server
        image: quay.io/brice/metrics-demo:v6
        ports:
        - containerPort: 3000
